--- 
repository: https://github.com/destructuring/gitscm-next
application: gitscm

user: buddhy
group: buddhy

ruby_loader: /usr/local/rvm/bin/rvm-exec
deploy_ruby: ree
app_ruby: 1.9.3

branches: [ master ]
branch_regex: /

chef_path: .

notify:
  nothing:
