--- 
repository: https://github.com/destructuring/gitscm-next
application: rtfm

user: zendesk
group: zendesk

ruby_loader: /usr/local/rvm/bin/rvm-exec
deploy_ruby: ree
app_ruby: 1.9.3

branches: [ master ]
branch_regex: /

chef_path: .
